language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libreoffice libreoffice-l10n-ja
  - curl https://raw.github.com/groonga/groonga/master/data/travis/setup.sh | sh
